server:
  servlet:
    context-path: /api
  port: 8080

spring:
#  profiles:
#    active: dev
  datasource:
#    url: jdbc:mysql://localhost:5432/crime_prediction?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    url: jdbc:postgresql://localhost:5432/crime_prediction
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
# Activer DevTools
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
      poll-interval: 1000
      quiet-period: 400


  jackson:
    coercion:
      empty-string: as_null
logging:
  level:
    org:
#      springframework: DEBUG
      springframework:
        boot:
          devtools: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  db-init: false
